import { StyleSheet, Dimensions } from "react-native";

export default StyleSheet.create({
  item: {
    marginTop: 5,
    marginBottom: 4,
    marginHorizontal: 0,
    fontSize: 11,
    fontWeight: 'bold',
  },
  title: {
    fontSize: 40,
    textAlign: 'left',
  },
  off: {
    textAlign: 'left',
    marginTop: 50,
    backgroundColor: 'red',
    width: 45,
    borderWidth: 2,
    marginHorizontal: 5,
    marginBottom: 10,
  },
  name: {
    backgroundColor: '#f9c2ff',
    padding: 125,
    margin: 'auto',
    textAlign: 'center',
    borderWidth: 2,
  },
  name2: {
    textDecorationLine: 'underline',
    fontSize: 20,
    marginHorizontal: 5,
  },
  des: {
    marginHorizontal: 5,
  },
  desContainer: {
    borderBottomWidth: 1,
    borderColor: 'grey',
    marginLeft: 5,
    marginRight: 5,
  },
  name3: {
    textAlign: 'center',
    fontSize: 30,
    textDecorationLine: 'underline',
  },
  websiteContainer: {
    borderBottomWidth: 1,
    paddingBottom: 10,
    paddingTop: 10,
    paddingLeft: 5,
    width: 400,
    borderColor: 'grey',
    marginLeft: 5,
    marginRight: 5,
  },
  name4: {
    color: 'grey',
    fontSize: 12,
  },
  comment: {
    color: 'grey',
    fontSize: 10,
  },
  website: {
    textAlign: 'left',
    color: 'blue',
    fontSize: 14,
  },
  locationContainer: {
    borderBottomWidth: 1,
    paddingBottom: 10,
    paddingTop: 10,
    paddingLeft: 5,
    width: 400,
    borderColor: 'grey',
    marginLeft: 5,
    marginRight: 5,
  },
  location: {
    textAlign: 'left',
    fontSize: 14,
  },
  name5: {
    color: 'grey',
    fontSize: 12,
  },
  emailContainer: {
    borderBottomWidth: 1,
    paddingBottom: 10,
    paddingTop: 10,
    paddingLeft: 5,
    width: 400,
    borderColor: 'grey',
    marginLeft: 5,
    marginRight: 5,
  },
  name6: {
    color: 'grey',
    fontSize: 12,
  },
  email: {
    textAlign: 'left',
    fontSize: 14,
  },
  name7: {
    color: 'grey',
    fontSize: 12,
  },
  phoneNumber: {
    textAlign: 'left',
    fontSize: 14,
  },
  comment2: {
    color: 'grey',
    fontSize: 10,
  },
  phoneNumberContainer: {
    paddingBottom: 10,
    paddingTop: 10,
    paddingLeft: 5,
    width: 400,
    borderColor: 'grey',
    marginLeft: 5,
    marginRight: 5,
  },
  map: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
  info: {
    fontWeight: 'bold',
    fontSize: 17,
    marginTop: 20,
    textAlign: 'center',
  },
  timerHeader: {
    textAlign: 'center',
    fontSize: 12,
  },
  timer: {
    color: 'black',
    fontSize: 40,
  },
  timerContainer: {
    marginLeft: 120,
    marginTop: 30,
  },
  start: {
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 5,
    marginTop: 75,
    backgroundColor: 'grey',
    width: 125,
    height: 50,
    textAlign: 'center',
    paddingTop: 13,
    paddingRight: 5,
    borderRadius: 5,
    borderWidth: 1,
    overflow: 'hidden',
    borderColor: 'grey',
  },
  pause: {
    fontSize: 16,
    fontWeight: 'bold',
    marginRight: 10,
    marginTop: 75,
    backgroundColor: 'grey',
    width: 125,
    height: 50,
    textAlign: 'center',
    paddingTop: 12,
    paddingRight: 5,
    borderRadius: 5,
    borderWidth: 1,
    overflow: 'hidden',
    borderColor: 'grey',
  },
  timerButtons: {
    flexDirection: 'row',
    marginLeft: 75,
  },
  image: {
    height: 138,
    width: '100%',
  },
  itemContainer: {
    marginRight: 20,
    marginLeft: 10,
    backgroundColor: 'grey',
    borderRadius: 10,
    overflow: 'hidden',
    width: 209,
  },
  add: {
    fontSize: 11,
    flexShrink: 1,
    flexWrap: 'wrap',
  },
  block: {
    fontSize: 11,
  },
  TextContainer: {
    width: '100%',
    height: 75,
    paddingHorizontal: 12,
  },
})
